import jsPDF from "jspdf";
import type { AIMemory } from "@/hooks/useAIMemory";

export function downloadMemoryPDF(memory: AIMemory) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Burgess Principle — AI Memory Summary", margin, y);
  y += 10;

  // Date
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Exported: ${new Date().toLocaleDateString()}`, margin, y);
  y += 4;
  if (memory.updatedAt) {
    doc.text(`Last updated: ${new Date(memory.updatedAt).toLocaleDateString()}`, margin, y);
    y += 4;
  }
  doc.text(`${memory.entries.length} memory ${memory.entries.length === 1 ? "entry" : "entries"}`, margin, y);
  y += 8;

  // Preferred tone
  if (memory.preferredTone) {
    checkPage(14);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(101, 67, 33); // warm brown
    doc.text("Preferred Tone", margin, y);
    y += 6;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    const lines = doc.splitTextToSize(memory.preferredTone, contentWidth);
    lines.forEach((line: string) => {
      checkPage(5);
      doc.text(line, margin, y);
      y += 4.5;
    });
    y += 4;
  }

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Entries
  memory.entries.forEach((entry, idx) => {
    checkPage(20);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(101, 67, 33);
    doc.text(`Session ${idx + 1} — ${new Date(entry.date).toLocaleDateString()}`, margin, y);
    y += 7;

    const sections: { label: string; content: string }[] = [];

    if (entry.effectiveStrategies.length > 0) {
      sections.push({ label: "Effective Strategies", content: entry.effectiveStrategies.join("; ") });
    }
    if (entry.situationNotes) {
      sections.push({ label: "Situation", content: entry.situationNotes });
    }
    if (entry.staffResponses) {
      sections.push({ label: "Staff Responses", content: entry.staffResponses });
    }
    if (entry.lessonsLearned) {
      sections.push({ label: "Lessons Learned", content: entry.lessonsLearned });
    }

    sections.forEach(({ label, content }) => {
      checkPage(12);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(80, 80, 80);
      doc.text(label, margin, y);
      y += 4.5;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(30, 30, 30);
      const lines = doc.splitTextToSize(content, contentWidth);
      lines.forEach((line: string) => {
        checkPage(5);
        doc.text(line, margin, y);
        y += 4.5;
      });
      y += 2;
    });

    // Entry divider
    y += 2;
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
  });

  // Footer
  checkPage(20);
  y += 2;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by The Burgess Principle companion tool.", margin, y);
  y += 4;
  doc.text("UK Certification Mark UK00004343685", margin, y);

  doc.save(`burgess-memory-${new Date().toISOString().slice(0, 10)}.pdf`);
}
