import jsPDF from "jspdf";
import type { Message } from "@/types/burgess";
import type { SavedConversation } from "@/hooks/useConversationStorage";

function roleLabel(role: Message["role"]): string {
  if (role === "staff-display") return "Suggested response (show to staff)";
  if (role === "user") return "Staff reply";
  return "AI adjustment";
}

export function generateLogPDF(conversation: SavedConversation): jsPDF {
  const { profile, messages } = conversation;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Burgess Principle — Conversation Log", margin, y);
  y += 10;

  // Metadata
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Name: ${profile.fullName}`, margin, y);
  y += 5;
  if (profile.adjustment) {
    doc.text(`Adjustment/Issue: ${profile.adjustment}`, margin, y);
    y += 5;
  }
  doc.text(`Country: ${profile.country}`, margin, y);
  y += 5;
  doc.text(`Date: ${new Date(conversation.createdAt).toLocaleDateString()}`, margin, y);
  y += 5;
  if (profile.context) {
    const contextLines = doc.splitTextToSize(`Context: ${profile.context}`, contentWidth);
    checkPage(contextLines.length * 4 + 2);
    doc.text(contextLines, margin, y);
    y += contextLines.length * 4 + 2;
  }

  // Divider
  y += 3;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Messages
  doc.setTextColor(0, 0, 0);
  messages.forEach((msg) => {
    const label = roleLabel(msg.role);
    const time = new Date(msg.timestamp).toLocaleTimeString();

    // Label
    checkPage(20);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(80, 80, 80);
    doc.text(`${label}  •  ${time}`, margin, y);
    y += 5;

    // Content
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    const lines = doc.splitTextToSize(msg.content, contentWidth);
    lines.forEach((line: string) => {
      checkPage(6);
      doc.text(line, margin, y);
      y += 4.5;
    });
    y += 4;
  });

  // Footer
  checkPage(20);
  y += 5;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by The Burgess Principle companion tool.", margin, y);
  y += 4;
  doc.text("UK Certification Mark UK00004343685", margin, y);

  return doc;
}

export function downloadLogPDF(conversation: SavedConversation) {
  const doc = generateLogPDF(conversation);
  const fileName = `burgess-log-${conversation.profile.fullName.replace(/\s+/g, "-").toLowerCase()}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(fileName);
}

export function getLogPDFBlob(conversation: SavedConversation): Blob {
  const doc = generateLogPDF(conversation);
  return doc.output("blob");
}
